language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - "$HOME/.npm"
jobs:
  fast_finish: true
  include:
    - stage: backend
        install:
          - cd ./backend
          - npm ci
    - stage: frontend
        install:
          - cd ./frontend
          - npm ci
    - stage: Lint backend
        install:
          - cd ./backend
          - npm ci
        script:
          - npm run lint